name: mini_guru
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  get_cli: ^1.8.1
  video_player: ^2.4.5
  share_plus: ^4.0.10+1
  url_launcher: ^6.1.5
  confetti: ^0.7.0
#  chewie: ^1.3.4
  video_viewer: ^1.2.7
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  bubble_bottom_bar: ^2.0.0
  expandable: ^5.0.1
  razorpay_flutter: ^1.3.2
  cupertino_icons: ^1.0.2
  onboarding_animation: ^0.0.1
  delayed_display: ^2.0.0
  flutter_facebook_auth: ^4.4.0
  shared_preferences: ^2.0.15
  google_sign_in: ^5.4.0
  firebase_auth: ^3.4.1
  pin_code_fields: ^7.4.0
  auto_size_text: ^3.0.0
  toggle_switch: ^2.0.1
  badges: ^2.0.3
  dotted_border: ^2.0.0+2
  lottie: ^1.4.0
  flutter_3d_choice_chip: ^0.1.4
  loading_animation_widget: ^1.2.0+2
  animated_bottom_navigation_bar: ^1.0.1
  font_awesome_flutter: ^10.1.0
  dropdown_button2: ^1.6.2
  shimmer: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  percent_indicator: ^4.2.2
  d_chart: ^0.0.4
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  flutter_slidable: ^0.6.0-nullsafety.0
  get: 4.6.5
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  custom_pin_screen: ^0.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

